### PR TITLE
Update ch.json

### PR DESCRIPTION
**Pull request by tiansongyu**
correct some words

### CODE REVIEW

**Comment by tallbl0nde** [comment]
Thanks, would you like me to add you to the repo? That way you can commit your changes directly without having to make a pull request everytime

**Comment by tiansongyu** [comment]
of course i do !!

**Comment by tallbl0nde** [comment]
Done :)

**Comment by tiansongyu** [comment]
coud  i ask a question? when i compile the switchthemeinstaller there are something wrong.

``linking SwitchThemesNX.elf
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.o: in function `NxEntry::NxThemeGetBgImage()':
BaseEntry.cpp:(.text._ZN7NxEntry17NxThemeGetBgImageEv[_ZN7NxEntry17NxThemeGetBgImageEv]+0x1d8): undefined reference to `DDSConv::ImageToDDS(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, int, int)'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.cpp:(.text._ZN7NxEntry17NxThemeGetBgImageEv[_ZN7NxEntry17NxThemeGetBgImageEv]+0x2e8): undefined reference to `DDSConv::GetError[abi:cxx11]()'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.o: in function `NxEntry::DoInstall(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
BaseEntry.cpp:(.text._ZN7NxEntry9DoInstallEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7NxEntry9DoInstallEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1bb8): undefined reference to `DDSConv::ImageToDDS(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, int, int)'

I thought because the version of the devkitA64 is too high.
but how do i downgrade the version of devkitA64 ?

**Comment by tallbl0nde** [comment]
I don't think that's due to devkitA64 (I don't know how to downgrade it either), it looks more like a linking error to me. I'm not sure how to fix it without having everything setup like you have, it may worth getting in contact with them.

**Comment by tiansongyu** [comment]
. I have give the issue to the author .. Thank you!

**Comment by tiansongyu** [comment]
sir !!! I found a amazing thing !!!! https://gbatemp.net/threads/collection-of-old-devkitpro-versions.526377/ if someone use the older version devkitA64 .
you can give it to him!!! this guy have the Collection of old devkitPro versions. Ithink this guy is the one who collect this things !!!! and this https://wii.leseratte10.de/devkitPro/

**Pull request merged**
